

CREATE SEQUENCE BOOK_CATEGORY_SEQ
  START WITH 1
  INCREMENT BY 1;

CREATE OR REPLACE TRIGGER BOOK_CATEGORY_ID_TRIGGER BEFORE
    INSERT ON BOOKCATEGORY FOR EACH ROW
BEGIN
    SELECT
        'bc'
        || TO_CHAR(BOOK_CATEGORY_SEQ.NEXTVAL, 'FM00000') INTO :NEW.CATEGORYID
    FROM
        DUAL;
END;
/

CREATE OR REPLACE PROCEDURE INSERT_BOOK_CATEGORY(
    P_CATEGORY_NAME IN BOOKCATEGORY.CATEGORYNAME%TYPE,
    P_CATEGORY_DESCRIPTION IN BOOKCATEGORY.CATEGORYDESCRIPTION%TYPE,
    P_CATEGORY_IMAGE IN BOOKCATEGORY.CATEGORYIMAGE%TYPE,
    P_NEW_ID OUT BOOKCATEGORY.CATEGORYID%TYPE
) AS
BEGIN
    INSERT INTO BOOKCATEGORY (
        CATEGORYNAME,
        CATEGORYDESCRIPTION,
        CATEGORYIMAGE
    ) VALUES (
        P_CATEGORY_NAME,
        P_CATEGORY_DESCRIPTION,
        P_CATEGORY_IMAGE
    ) RETURNING CATEGORYID INTO P_NEW_ID;
END;
/


CallableStatement stmt = connection.prepareCall("{call insert_book_category(?, ?, ?, ?)}");
stmt.setString(1, categoryName);
stmt.setString(2, categoryDescription);
stmt.setString(3, categoryImage);
stmt.registerOutParameter(4, Types.VARCHAR);
stmt.execute();
String newId = stmt.getString(4);